line-length = 100
target-version = "py311"

[lint]
select = [
  "E",
  "F",
  "I",
  "B",
  "UP",
  "N",
  "S",
  "RET",
  "C4",
  "RUF"
]
ignore = [
  "S101"  # Allow use of assert in tests
]

[lint.per-file-ignores]
"tests/**" = ["S101"]

[lint.isort]
known-first-party = ["show_scribe"]
section-order = ["future", "standard-library", "third-party", "first-party", "local-folder"]
